version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/medical_db
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  postgres_data: